//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Data.Entity.Design.UI.Views.Dialogs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DialogsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Data.Entity.Design.UI.Views.Dialogs.DialogsResource", typeof(DialogsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Button.
        /// </summary>
        public static string CancelButton_AccessibleName {
            get {
                return ResourceManager.GetString("CancelButton_AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton_Text {
            get {
                return ResourceManager.GetString("CancelButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        public static string CancellingButton_Text {
            get {
                return ResourceManager.GetString("CancellingButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a complex type:.
        /// </summary>
        public static string ComplexTypePickerDialog_Prompt {
            get {
                return ResourceManager.GetString("ComplexTypePickerDialog_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Complex Property.
        /// </summary>
        public static string ComplexTypePickerDialog_Title {
            get {
                return ResourceManager.GetString("ComplexTypePickerDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete these items?.
        /// </summary>
        public static string ConfirmDeleteDialog_DescriptionLabel_Text {
            get {
                return ResourceManager.GetString("ConfirmDeleteDialog_DescriptionLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string ConfirmDeleteDialog_Title {
            get {
                return ResourceManager.GetString("ConfirmDeleteDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Delete.
        /// </summary>
        public static string DeleteButton_Text {
            get {
                return ResourceManager.GetString("DeleteButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following tables and views in the store model will no longer be mapped.  Do you want them deleted?.
        /// </summary>
        public static string DeleteStorageEntitySetsDescription {
            get {
                return ResourceManager.GetString("DeleteStorageEntitySetsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Unmapped Tables and Views.
        /// </summary>
        public static string DeleteStorageEntitySetsDialogTitle {
            get {
                return ResourceManager.GetString("DeleteStorageEntitySetsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Storage Entity Sets.
        /// </summary>
        public static string DeleteStorageEntitySetsListBox_AccessibleName {
            get {
                return ResourceManager.GetString("DeleteStorageEntitySetsListBox_AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string FinishButton_Text {
            get {
                return ResourceManager.GetString("FinishButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Association Name:.
        /// </summary>
        public static string NewAssociationDialog_AssociationNameLabel {
            get {
                return ResourceManager.GetString("NewAssociationDialog_AssociationNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &amp;foreign key properties to the &apos;{0}&apos; Entity.
        /// </summary>
        public static string NewAssociationDialog_CreateForeignKeysLabel {
            get {
                return ResourceManager.GetString("NewAssociationDialog_CreateForeignKeysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add foreign key properties.
        /// </summary>
        public static string NewAssociationDialog_CreateForeignKeysLabel_Default {
            get {
                return ResourceManager.GetString("NewAssociationDialog_CreateForeignKeysLabel_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string NewAssociationDialog_EndLabel {
            get {
                return ResourceManager.GetString("NewAssociationDialog_EndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify that the Association name is unique..
        /// </summary>
        public static string NewAssociationDialog_EnsureUniqueNameMsg {
            get {
                return ResourceManager.GetString("NewAssociationDialog_EnsureUniqueNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify that the NavigationProperty name is unique..
        /// </summary>
        public static string NewAssociationDialog_EnsureUniquePropertyNameMsg {
            get {
                return ResourceManager.GetString("NewAssociationDialog_EnsureUniquePropertyNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity 1.
        /// </summary>
        public static string NewAssociationDialog_Entity1AccessibleName {
            get {
                return ResourceManager.GetString("NewAssociationDialog_Entity1AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity 2.
        /// </summary>
        public static string NewAssociationDialog_Entity2AccessibleName {
            get {
                return ResourceManager.GetString("NewAssociationDialog_Entity2AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Entity:.
        /// </summary>
        public static string NewAssociationDialog_EntityLabel {
            get {
                return ResourceManager.GetString("NewAssociationDialog_EntityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explanation box.
        /// </summary>
        public static string NewAssociationDialog_ExplanationBoxAccessibleName {
            get {
                return ResourceManager.GetString("NewAssociationDialog_ExplanationBoxAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can have {1} instance of {2}. Use {0}.{3} to access the {2} instance..
        /// </summary>
        public static string NewAssociationDialog_ExplanationText1 {
            get {
                return ResourceManager.GetString("NewAssociationDialog_ExplanationText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can have {1} instance of {2}..
        /// </summary>
        public static string NewAssociationDialog_ExplanationText1EmptyNavProp {
            get {
                return ResourceManager.GetString("NewAssociationDialog_ExplanationText1EmptyNavProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can have {1} instances of {2}. Use {0}.{3} to access the {2} instances..
        /// </summary>
        public static string NewAssociationDialog_ExplanationText2 {
            get {
                return ResourceManager.GetString("NewAssociationDialog_ExplanationText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can have {1} instances of {2}..
        /// </summary>
        public static string NewAssociationDialog_ExplanationText2EmptyNavProp {
            get {
                return ResourceManager.GetString("NewAssociationDialog_ExplanationText2EmptyNavProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Association name is not valid..
        /// </summary>
        public static string NewAssociationDialog_InvalidAssociationNameMsg {
            get {
                return ResourceManager.GetString("NewAssociationDialog_InvalidAssociationNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NavigationProperty name is not valid..
        /// </summary>
        public static string NewAssociationDialog_InvalidNavigationPropertyNameMsg {
            get {
                return ResourceManager.GetString("NewAssociationDialog_InvalidNavigationPropertyNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplicity 1.
        /// </summary>
        public static string NewAssociationDialog_Multiplicity1AccessibleName {
            get {
                return ResourceManager.GetString("NewAssociationDialog_Multiplicity1AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplicity 2.
        /// </summary>
        public static string NewAssociationDialog_Multiplicity2AccessibleName {
            get {
                return ResourceManager.GetString("NewAssociationDialog_Multiplicity2AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Multiplicity:.
        /// </summary>
        public static string NewAssociationDialog_MultiplicityLabel {
            get {
                return ResourceManager.GetString("NewAssociationDialog_MultiplicityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Property 1.
        /// </summary>
        public static string NewAssociationDialog_NavigationProperty1AccessibleName {
            get {
                return ResourceManager.GetString("NewAssociationDialog_NavigationProperty1AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Property 2.
        /// </summary>
        public static string NewAssociationDialog_NavigationProperty2AccessibleName {
            get {
                return ResourceManager.GetString("NewAssociationDialog_NavigationProperty2AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Navigation Property:.
        /// </summary>
        public static string NewAssociationDialog_NavigationPropertyLabel {
            get {
                return ResourceManager.GetString("NewAssociationDialog_NavigationPropertyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Association.
        /// </summary>
        public static string NewAssociationDialog_Title {
            get {
                return ResourceManager.GetString("NewAssociationDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Base type:.
        /// </summary>
        public static string NewEntityDialog_BaseTypeLabel {
            get {
                return ResourceManager.GetString("NewEntityDialog_BaseTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create key property.
        /// </summary>
        public static string NewEntityDialog_CreateKeyLabel {
            get {
                return ResourceManager.GetString("NewEntityDialog_CreateKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify that the EntityType name is unique..
        /// </summary>
        public static string NewEntityDialog_EnsureUniqueNameMsg {
            get {
                return ResourceManager.GetString("NewEntityDialog_EnsureUniqueNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify that the EntitySet name is unique..
        /// </summary>
        public static string NewEntityDialog_EnsureUniqueSetNameMsg {
            get {
                return ResourceManager.GetString("NewEntityDialog_EnsureUniqueSetNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Entity name:.
        /// </summary>
        public static string NewEntityDialog_EntityNameLabel {
            get {
                return ResourceManager.GetString("NewEntityDialog_EntityNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity &amp;Set:.
        /// </summary>
        public static string NewEntityDialog_EntitySetLabel {
            get {
                return ResourceManager.GetString("NewEntityDialog_EntitySetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EntityType name is not valid..
        /// </summary>
        public static string NewEntityDialog_InvalidEntityNameMsg {
            get {
                return ResourceManager.GetString("NewEntityDialog_InvalidEntityNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EntitySet name is not valid..
        /// </summary>
        public static string NewEntityDialog_InvalidEntitySetMsg {
            get {
                return ResourceManager.GetString("NewEntityDialog_InvalidEntitySetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Key Property name is not valid..
        /// </summary>
        public static string NewEntityDialog_InvalidKeyPropertyNameMsg {
            get {
                return ResourceManager.GetString("NewEntityDialog_InvalidKeyPropertyNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Property.
        /// </summary>
        public static string NewEntityDialog_KeyPropertyLabel {
            get {
                return ResourceManager.GetString("NewEntityDialog_KeyPropertyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string NewEntityDialog_PropertiesLabel {
            get {
                return ResourceManager.GetString("NewEntityDialog_PropertiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &amp;name:.
        /// </summary>
        public static string NewEntityDialog_PropertyNameLabel {
            get {
                return ResourceManager.GetString("NewEntityDialog_PropertyNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &amp;type:.
        /// </summary>
        public static string NewEntityDialog_PropertyTypeLabel {
            get {
                return ResourceManager.GetString("NewEntityDialog_PropertyTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Entity.
        /// </summary>
        public static string NewEntityDialog_Title {
            get {
                return ResourceManager.GetString("NewEntityDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Function Import.
        /// </summary>
        public static string NewFunctionImportDialog_AddFunctionImportTitle {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_AddFunctionImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Return Type shape cannot be inferred..
        /// </summary>
        public static string NewFunctionImportDialog_CannotInferReturnTypeShapeMsg {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_CannotInferReturnTypeShapeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Return Type Shape.
        /// </summary>
        public static string NewFunctionImportDialog_ClickToExecute {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_ClickToExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex Types.
        /// </summary>
        public static string NewFunctionImportDialog_ComplexTypeReturnAccessibleName {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_ComplexTypeReturnAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Complex:.
        /// </summary>
        public static string NewFunctionImportDialog_ComplexTypeReturnLabel {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_ComplexTypeReturnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the stored procedure or function {0}. This may be a temporary inability to read from the database or the stored procedure or function may have been deleted from the database..
        /// </summary>
        public static string NewFunctionImportDialog_CouldNotFindStoredProcedure {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_CouldNotFindStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Function Import.
        /// </summary>
        public static string NewFunctionImportDialog_EditFunctionImportTitle {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_EditFunctionImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;None.
        /// </summary>
        public static string NewFunctionImportDialog_EmptyReturnTypeLabel {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_EmptyReturnTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify that the FunctionImport name is unique..
        /// </summary>
        public static string NewFunctionImportDialog_EnsureUniqueNameMsg {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_EnsureUniqueNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities Type.
        /// </summary>
        public static string NewFunctionImportDialog_EntityTypeReturnAccessibleName {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_EntityTypeReturnAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Entities:.
        /// </summary>
        public static string NewFunctionImportDialog_EntityTypeReturnLabel {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_EntityTypeReturnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting Return Type....
        /// </summary>
        public static string NewFunctionImportDialog_Executing {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Function Import Name:.
        /// </summary>
        public static string NewFunctionImportDialog_FunctionImportLabel {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_FunctionImportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception of type &quot;{0}&quot; occurred while attempting to get columns information.
        ///The exception message is:
        ///{1}.
        /// </summary>
        public static string NewFunctionImportDialog_GetColumnInfoException {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_GetColumnInfoException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Function Import name is not valid..
        /// </summary>
        public static string NewFunctionImportDialog_InvalidFunctionImportNameMsg {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_InvalidFunctionImportNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing composable Function Imports is not supported for EDMX files with version less than or equal to {0}.
        /// </summary>
        public static string NewFunctionImportDialog_IsComposableTooltipText {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_IsComposableTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected stored procedure or function returns no columns..
        /// </summary>
        public static string NewFunctionImportDialog_NoColumnsReturned {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_NoColumnsReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A database connection could not be found for this model..
        /// </summary>
        public static string NewFunctionImportDialog_NoConnectionMsg {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_NoConnectionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Supported.
        /// </summary>
        public static string NewFunctionImportDialog_NotSupportedColumnType {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_NotSupportedColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not a valid name for a complex type..
        /// </summary>
        public static string NewFunctionImportDialog_NotValidComplexTypeName {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_NotValidComplexTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Type:.
        /// </summary>
        public static string NewFunctionImportDialog_ReturnTypeLabel {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_ReturnTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string NewFunctionImportDialog_ReturnTypeListAddAction {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_ReturnTypeListAddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string NewFunctionImportDialog_ReturnTypeListDeleteAction {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_ReturnTypeListDeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NewFunctionImportDialog_ReturnTypeListNoAction {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_ReturnTypeListNoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string NewFunctionImportDialog_ReturnTypeListUpdateAction {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_ReturnTypeListUpdateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-&gt;{1}.
        /// </summary>
        public static string NewFunctionImportDialog_ReturnTypeListViewItemChange {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_ReturnTypeListViewItemChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scalars.
        /// </summary>
        public static string NewFunctionImportDialog_ScalarsTypeReturnAccessibleName {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_ScalarsTypeReturnAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Scalars:.
        /// </summary>
        public static string NewFunctionImportDialog_ScalarsTypeReturnLabel {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_ScalarsTypeReturnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Stored Procedure to enable return type shape detection..
        /// </summary>
        public static string NewFunctionImportDialog_SelectStoredProcedure {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_SelectStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored &amp;Procedure Name:.
        /// </summary>
        public static string NewFunctionImportDialog_StoredProcNameLabel {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_StoredProcNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Function Import.
        /// </summary>
        public static string NewFunctionImportDialog_Title {
            get {
                return ResourceManager.GetString("NewFunctionImportDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the base and derived entities to create a new inheritance relationship..
        /// </summary>
        public static string NewInheritanceDialog_InfoText {
            get {
                return ResourceManager.GetString("NewInheritanceDialog_InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a &amp;base entity:.
        /// </summary>
        public static string NewInheritanceDialog_SelectBaseEntity {
            get {
                return ResourceManager.GetString("NewInheritanceDialog_SelectBaseEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a &amp;derived entity:.
        /// </summary>
        public static string NewInheritanceDialog_SelectDerivedEntity {
            get {
                return ResourceManager.GetString("NewInheritanceDialog_SelectDerivedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Inheritance.
        /// </summary>
        public static string NewInheritanceDialog_Title {
            get {
                return ResourceManager.GetString("NewInheritanceDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Button.
        /// </summary>
        public static string NoButton_AccessibleName {
            get {
                return ResourceManager.GetString("NoButton_AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;No.
        /// </summary>
        public static string NoButton_Text {
            get {
                return ResourceManager.GetString("NoButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK Button.
        /// </summary>
        public static string OKButton_AccessibleName {
            get {
                return ResourceManager.GetString("OKButton_AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKButton_Text {
            get {
                return ResourceManager.GetString("OKButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent Key.
        /// </summary>
        public static string RefConstraintDialog_DependentKeyHeader {
            get {
                return ResourceManager.GetString("RefConstraintDialog_DependentKeyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent Property.
        /// </summary>
        public static string RefConstraintDialog_DependentKeyHeader_SupportFKs {
            get {
                return ResourceManager.GetString("RefConstraintDialog_DependentKeyHeader_SupportFKs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent:.
        /// </summary>
        public static string RefConstraintDialog_DependentLabel {
            get {
                return ResourceManager.GetString("RefConstraintDialog_DependentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following list of dependent key properties ({0}) are each mapped to more than one principal key property. Please ensure there is a maximum of one mapping for each dependent key property..
        /// </summary>
        public static string RefConstraintDialog_DependentPropMappedMultipleTimes {
            get {
                return ResourceManager.GetString("RefConstraintDialog_DependentPropMappedMultipleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal Key.
        /// </summary>
        public static string RefConstraintDialog_PrincipalKeyHeader {
            get {
                return ResourceManager.GetString("RefConstraintDialog_PrincipalKeyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Principal:.
        /// </summary>
        public static string RefConstraintDialog_PrincipalLabel {
            get {
                return ResourceManager.GetString("RefConstraintDialog_PrincipalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referential Constraint.
        /// </summary>
        public static string RefConstraintDialog_Title {
            get {
                return ResourceManager.GetString("RefConstraintDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Build and deploy database project &apos;{0}&apos; to Debug database.
        /// </summary>
        public static string RefreshFunctionImportsDialog_chkBuildAndDeploy_Text {
            get {
                return ResourceManager.GetString("RefreshFunctionImportsDialog_chkBuildAndDeploy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the database project &apos;{0}&apos;.
        /// </summary>
        public static string RefreshFunctionImportsDialog_Error_NoProject {
            get {
                return ResourceManager.GetString("RefreshFunctionImportsDialog_Error_NoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A database project reference must be specified for this model.
        /// </summary>
        public static string RefreshFunctionImportsDialog_Error_NoReference {
            get {
                return ResourceManager.GetString("RefreshFunctionImportsDialog_Error_NoReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only references of type &apos;{0}&apos; are supported for this operation.
        /// </summary>
        public static string RefreshFunctionImportsDialog_Error_OnlyDbProject {
            get {
                return ResourceManager.GetString("RefreshFunctionImportsDialog_Error_OnlyDbProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Views, Functions, and Function Imports for &apos;{0}&apos;.
        /// </summary>
        public static string RefreshFunctionImportsDialog_Title {
            get {
                return ResourceManager.GetString("RefreshFunctionImportsDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property name cannot be the same as the entity name..
        /// </summary>
        public static string SameEntityAndPropertyNameMsg {
            get {
                return ResourceManager.GetString("SameEntityAndPropertyNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes Button.
        /// </summary>
        public static string YesButton_AccessibleName {
            get {
                return ResourceManager.GetString("YesButton_AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Yes.
        /// </summary>
        public static string YesButton_Text {
            get {
                return ResourceManager.GetString("YesButton_Text", resourceCulture);
            }
        }
    }
}
